
version: '3.3'

services:
  postgres:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=study_reminder_dev
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123

  # database for testing
  postgres_test:
    image: postgres:10.1-alpine
    ports:
      - "5432"
    environment:
      - POSTGRES_DB=study_reminder_test
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=dev123

volumes:
  postgres_data: